In [3]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Suppress TensorFlow logging (1)
import tensorflow as tf

# Rank 1 Tensor

In [ ]:
# Rank 1 Tensor (Vector)
x = tf.constant(4 , shape=(1,2) , name="X")
y = tf.constant(4)

print ("Value of Tensor X" , x)
print ("Value of Tensor Y" , y)

print(x + y)  # Addition
print(x - y)  # Subtraction


Value of Tensor X tf.Tensor([[4 4]], shape=(1, 2), dtype=int32)
Value of Tensor Y tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[8 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[0 0]], shape=(1, 2), dtype=int32)


# Rank 2 Tensor

In [8]:
# Rank 2 Tensor (Matrix)
a = tf.constant([[1,2],[3,4]] , name="A")
b = tf.constant([[5,6],[7,8]] , name="B")
print ("Value of Tensor A" , a)
print ("Value of Tensor B" , b)

print(a + b)  # Addition
print(a - b)  # Subtraction

Value of Tensor A tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Value of Tensor B tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


In [ ]:
z = tf.zeros((2,3) , name="Z")  # Rank 2 Tensor of zeros
print ("Value of Tensor Z \n" , z)
print (end="\n")

x = tf.ones((2,3) , name="X")  # Rank 2 Tensor of ones
print ("Value of Tensor X \n" , x)
print (end="\n")
# Diagonal matrix
y = tf.eye(3 , name="Y")  # Rank 2 Identity Tensor
print ("Value of Tensor Y \n" , y)
print (end="\n")
# Random
v = tf.random.normal((3,3) , mean=0 , stddev=1 , name="V")  # Rank 2 Tensor of random values from a normal distribution
print ("Value of Tensor V \n" , v)
print (end="\n")
# Uniform distribution
w = tf.random.uniform((3,3) , minval=0 , maxval=1 , name="W")  # Rank 2 Tensor of random values from a uniform distribution
print ("Value of Tensor W \n" , w)
print (end="\n")

Value of Tensor Z 
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

Value of Tensor X 
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

Value of Tensor Y 
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)

Value of Tensor V 
 tf.Tensor(
[[ 0.6462567   1.1329004   0.96233606]
 [-0.90693575  2.0132062  -1.2244143 ]
 [ 0.58398557 -1.8142331  -0.844504  ]], shape=(3, 3), dtype=float32)

Value of Tensor W 
 tf.Tensor(
[[0.31438935 0.58290493 0.44921243]
 [0.10423625 0.6819563  0.02912474]
 [0.4898969  0.94221854 0.13531375]], shape=(3, 3), dtype=float32)



# Rank 3 Tensor

In [25]:
# Rank 3 Tensor
c = tf.constant([[[1,2 , 3],[3,4 , 5]],[[5,6, 7],[7,8, 9]]] , name="C")
print ("Value of Tensor C" , c)
print (end="\n")

d = tf.zeros((3,3,3) , name="D")  # Rank 3 Tensor of zeros
print ("Value of Tensor D" , d)
print (end="\n")


Value of Tensor C tf.Tensor(
[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]], shape=(2, 2, 3), dtype=int32)

Value of Tensor D tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)



# Elementwise Operations

In [ ]:
a = tf.constant([1,2,3] , name="A")
b = tf.constant([4,5,6] , name="B")

res = tf.add(a,b)  # Element-wise addition
print ("Result of A + B \n" , res)

add_res = a + b
print ("Result of A + B using operator \n" , add_res)
print (end="\n")

#=======================================================

sub = tf.subtract(a,b)  # Element-wise subtraction
print ("Result of A - B \n" , sub)

sub_res = a - b
print ("Result of A - B using operator \n" , sub_res)
print (end="\n")

#=======================================================
# here we should put into consideration matrices multiplication rules of the shape of both
mul = tf.multiply(a,b)  # Element-wise multiplication
print ("Result of A * B \n" , mul)

mul_res = a * b
print ("Result of A * B using operator \n" , mul_res)
print (end="\n")

#=======================================================

div = tf.divide(a,b)  # Element-wise division
print ("Result of A / B \n" , div)

div_res = a / b
print ("Result of A / B using operator \n" , div_res)
print (end="\n")


Result of A + B 
 tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Result of A + B using operator 
 tf.Tensor([5 7 9], shape=(3,), dtype=int32)

Result of A - B 
 tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
Result of A - B using operator 
 tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)

Result of A * B 
 tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Result of A * B using operator 
 tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)

Result of A / B 
 tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
Result of A / B using operator 
 tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)



# Slicing , Indexing

In [36]:
x = tf.constant([[1,2 , 5 , 6],[3,4 , 6 , 7]] , name="X")
print (x[0])
print (x[1])
print (x[0][1])
print (x[:,0]) # all rows and the first column
print (x[:,1]) # all rows and the second column
print (x[0,:]) # all columns and the first row

tf.Tensor([1 2 5 6], shape=(4,), dtype=int32)
tf.Tensor([3 4 6 7], shape=(4,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor([1 2 5 6], shape=(4,), dtype=int32)


# Reshaping

In [ ]:
x = tf.constant([[1,2],[3,4]] , name="X")
print (x)
x = tf.reshape(x , (4,1))  # Reshape to a column vector
print (x)
x = tf.reshape(x , (1,4))  # Reshape back to original shape
print (x)
# must have the same number of elements before and after reshaping

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


# Tensor Conversion


In [42]:
import numpy as np
a = np.array([[1,2],[3,4]])
print (a)

x = tf.convert_to_tensor(a , dtype=tf.int32)  # Convert NumPy array to TensorFlow tensor
print (x)

[[1 2]
 [3 4]]
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
